# Generated by Django 4.2.13 on 2024-11-27 05:33

import API.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='Extension',
            field=models.CharField(default='.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='Status',
            field=models.IntegerField(choices=[(0, 'INDISPONIVEL'), (1, 'DISPONIVEL')], default=API.enums.Status['DISPONIVEL']),
        ),
    ]
