# Generated by Django 4.2.13 on 2024-11-28 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_photo_extension_alter_car_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='Extension',
        ),
    ]
