# Generated by Django 4.2.13 on 2024-11-28 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_photo_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.photo'),
        ),
    ]
